FROM python:3.10-slim

# install necessary system dependencies for PostgreSQL client and Python packages
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# get the requirements for the consumer from the config/ folder
COPY config/requirements-consumer.txt ./requirements-consumer.txt
RUN pip install --no-cache-dir -r requirements-consumer.txt

# get the pre-trained models and metrics from the models/ folder
COPY models/linear_regression_feat_exp.pkl .
COPY models/RobustScaler_feat_exp.pkl .
COPY models/train_metrics_feature_expansion.npz .
COPY models/nids_mlp_model1.joblib .
COPY models/nids_scaler1.joblib .

# copy code from src/ to /app in the container
COPY src/ .

# create logs directory for storing alerts
RUN mkdir -p /app/logs