FROM python:3.10-slim

WORKDIR /app

# Παίρνουμε τα requirements από τον φάκελο config/
COPY config/requirements-consumer.txt ./requirements-consumer.txt
RUN pip install --no-cache-dir -r requirements-consumer.txt

# Παίρνουμε τα μοντέλα από τον φάκελο models/
COPY models/linear_regression_feat_exp.pkl .
COPY models/RobustScaler_feat_exp.pkl .
COPY models/train_metrics_feature_expansion.npz .

# Αντιγράφουμε ΟΛΟ τον κώδικα από τον φάκελο src/
COPY src/ .

# create logs directory for storing alerts
RUN mkdir -p /app/logs