FROM python:3.10-slim

# install necessary system dependencies for packet capturing
RUN apt-get update && apt-get install -y \
    libpcap-dev \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Παίρνουμε τα requirements από τον φάκελο config/
COPY config/requirements-producer.txt ./requirements-producer.txt
RUN pip install --no-cache-dir -r requirements-producer.txt

# Αντιγράφουμε ΟΛΟ τον κώδικα από τον φάκελο src/ χύμα μέσα στο /app του container
COPY src/ .

CMD ["python3", "Producer_kafka.py"]