FROM python:3.10-slim

# install necessary system dependencies for packet capturing
RUN apt-get update && apt-get install -y \
    libpcap-dev \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# get the requirements for the producer from the config/ folder
COPY config/requirements-producer.txt ./requirements-producer.txt
RUN pip install --no-cache-dir -r requirements-producer.txt

# copy code from src/ to /app in the container
COPY src/ .

CMD ["python3", "Producer_kafka.py"]